module.exports = [
	{heapu8                      : /[\/\\]heapu8\.exclude/},
	{j                           : /[\/\\]j\.raw\.exclude/},
	{x                           : /[\/\\]x\.raw\.exclude/},
	{o                           : /[\/\\]o\.raw\.exclude/},
	{s                           : /[\/\\]s\.raw\.exclude/},
	{l                           : /[\/\\]l\.raw\.exclude/},
	{g                           : /[\/\\]g\.raw\.exclude/},
	{h                           : /[\/\\]h\.raw\.exclude/},
	{g1                          : /[\/\\]g1\.raw\.exclude/},
	{e                           : /[\/\\]e\.raw\.exclude/},
	{d                           : /[\/\\]d\.raw\.exclude/},
	{d1                          : /[\/\\]d1\.raw\.exclude/},
	{d2                          : /[\/\\]d2\.raw\.exclude/},
	{f                           : /[\/\\]f\.raw\.exclude/},
	{e1                          : /[\/\\]e1\.raw\.exclude/},
	{c                           : /[\/\\]c\.raw\.exclude/},
	{c1                          : /[\/\\]c1\.raw\.exclude/},
	{c2sass                      : /[\/\\](c2\.raw|sass)\.exclude/},
	{module                      : /[\/\\]module\.raw\.exclude/},

	{vlpostcss                   : /vue-loader|postcss/},
	{jszippakovtc                : /jszip|pako|vue-template-compiler/},
	{smzdl                       : /source-map|vue|zero-dev-lib/},

	{types                       : /@babel[\/\\]types/},
	{parser                      : /@babel[\/\\]parser/},
	{chg                         : /@babel[\/\\](core|helpers|generator)/},
	{transform                   : /@babel[\/\\]plugin-transform-/},
	{blontypes                   : /babylon|babel-types/},
	{babelat                     : /@babel/},
	{babel                       : /babel/},

	{binaryproperty              : /Binary_Property/},
	{regunicodeprop              : /regenerate-unicode-properties/},
	{reuclesusvccgrgt            : /regexpu-core|lodash|esutils|semver|color-convert|globals|regenerator-transform/},
	{crypto                      : /crypto|sha|elliptic|bn|rand|pbkdf|des|aes|ecies|hash|diffie-hellman|esc|md5|asn|ripemd|hmac|token|rsa/}
];